database:
  host: db
  port: 5432
  name: p2p_bot
  user: antonmiklis
  password: ${DB_PASSWORD}
  ssl: disable
redis:
  host: cache
  port: 6379
  db: 0
rabbitmq:
  url: amqp://guest:guest@rabbitmq:5672/
telegram:
  api-key: ${BOT_TOKEN}
  bot-link: ${BOT_LINK}
exchange:
  max-retries: 20
  retry-delay: 30
website:
  port: 443
  backend-port: 8443
  key-file: /app/certs/server.key
  cert-file: /app/certs/server.crt
  front-url: http://front:3000
  jwt-secret: ${JWT_SECRET}

